env:
  global:
    # AWS S3 details so travis can post build artifacts
    - "ARTIFACTS_AWS_REGION=us-west-2"
    - "ARTIFACTS_S3_BUCKET=public.numenta.org"
    - secure: "NnM6+xBK5gPaiErwg21gleXgOr+6u2RjItQ1yeIx2VnoPFZ37wQMNQCIsHum\nSjos5N0HEeBm0/JXFQlq+oQk05mafJC1OTFqUWLwgvRcf9X5yU+KwCVWuyGG\nPDcqyeSACb2MSnNrCuheNmQQ6XlwxjQ9ZqMuJ47l2kC+KSsVYb0="
    - secure: "qxCzKQqVWQ3q7TCSXoSRcVOongc3O9xYyandb2029NW99JItJUd4xGpNYmaq\nksJXOG8/UpJd+lGMvcfNv12ohNN/jbPuh/kp9gQ5Xt5Y8RUdnLm7RHW5Tb1D\n7ERPwTE/EB9Tw5NJE2Tev+bZYlK/r9G7sR/1n7LqEvKex0b8/aY="

before_script:
  - gem install travis-artifacts
  - sudo apt-get install texlive
  # Yes, this is ridiculous.
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install pandoc
  - export PATH=${PATH}:~/.cabal/bin

script: 
  - pandoc ${TRAVIS_BUILD_DIR}/HTM_CLA/HTM_Cortical_Learning_Algorithms.tex -f latex -t html -s -o cla.html

after_script:
  - "travis-artifacts upload --target-path cla/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --path cla.html"
